// Sanity schema for AI-managed FAQs
export const faqSchema = {
  name: 'faq',
  title: 'FAQ',
  type: 'document',
  fields: [
    {
      name: 'question',
      title: 'Question',
      type: 'string',
      validation: (rule: any) => rule.required()
    },
    {
      name: 'answer',
      title: 'Answer',
      type: 'text',
      validation: (rule: any) => rule.required()
    },
    {
      name: 'category',
      title: 'Category',
      type: 'string',
      options: {
        list: [
          { title: 'General', value: 'general' },
          { title: 'Services', value: 'services' },
          { title: 'Mining', value: 'mining' },
          { title: 'Safety', value: 'safety' },
          { title: 'Careers', value: 'careers' }
        ]
      }
    },
    {
      name: 'aiGenerated',
      title: 'AI Generated',
      type: 'boolean',
      description: 'Was this FAQ generated by AI?',
      initialValue: false
    },
    {
      name: 'priority',
      title: 'Priority',
      type: 'number',
      description: 'Higher numbers appear first',
      initialValue: 0
    },
    {
      name: 'isActive',
      title: 'Is Active',
      type: 'boolean',
      initialValue: true
    },
    {
      name: 'createdAt',
      title: 'Created At',
      type: 'datetime',
      initialValue: () => new Date().toISOString()
    }
  ],
  preview: {
    select: {
      title: 'question',
      subtitle: 'category',
      media: 'aiGenerated'
    },
    prepare(selection: any) {
      const { title, subtitle, media } = selection
      return {
        title,
        subtitle: `${subtitle} ${media ? '(AI Generated)' : ''}`,
      }
    }
  }
}
